### ISSUE TITLE
Hardcoded Prague departure points

### ISSUE THREAD

**Issue by sabatale** [barjin/flight-tickets-scraper#3]
Great starting point! Could you confirm whether Prague is hardcoded in the HEX?

If so, would you mind letting us know what to replace with `...new TextEncoder().encode(origin_iata)`?

```
const data = [
            0x08, 0x1C, 0x10, 0x02, 0x1A, 0x23, 0x6A, 0x0C, 0x08, 0x02, 0x12, 0x08,
            0x2F, 0x6D, 0x2F, 0x30, 0x35, 0x79, 0x77, 0x67, 0x12, 0x0A, ...new TextEncoder().encode(new Date(dateFrom).toISOString().split('T')[0]), 0x72, 0x07, 0x08, 0x01,
            0x12, 0x03, ...new TextEncoder().encode(iata), 0x1A, 0x23, 0x6A, 0x07, 0x08, 0x01, 0x12,
            0x03, ...new TextEncoder().encode(iata), 0x12, 0x0A, ...new TextEncoder().encode(new Date(dateTo).toISOString().split('T')[0]), 0x72, 0x0C, 0x08, 0x02, 0x12, 0x08, 0x2F, 0x6D,
            0x2F, 0x30, 0x35, 0x79, 0x77, 0x67, 0x70, 0x01, 0x82, 0x01, 0x0B, 0x08
        ];
```

Same with the `____________AUABSAGYAQE` value.

@barjin

**Comment by barjin** [comment]
Hi @sabatale - I'll be honest with you - it has been a long time since I've worked on this project, so the details are a bit hazy :) If you're looking for something a bit more sophisticated and complete, check out [my other repo here](https://github.com/barjin/plane-ticket-scraper). 

That one scrapes Google Flights using their (partially reverse-engineered) protobuf format, so it's much faster, gives better results and you can actually parametrize the search without decoding HEX values 😅 

See you there! (I'll archive this repo in a few moments).

**Comment by sabatale** [comment]
No worries, appreciate the reply! 🎄⭐
